Restore Class Names in decay and mutators Folders for Backward Compatibility
knakamura13/mlrose-ky pull request #9
Opened 2024-08-26 23:25 UTC by gitongah

This pull request addresses the renaming of classes in the decay and mutators folders to their original names, ensuring backward compatibility with existing codebases that rely on these class names.

2024-08-27 10:04 UTC, knakamura13 requested changes
Added comments indicating changes that need to be made.

Also, before creating a pull request, try to make sure your branch is up to date with the main branch in my repo.
There are probably better ways to do this, but you can just follow these steps before you submit a pull request to sync my repo with yours:
1. `git fetch upstream` (or `git fetch --all` for simplicity)
2. `git checkout main`
3. `git merge --ff-only upstream/main`
4. `git checkout <your PR branch>`
5. `git merge main` (or `git rebase main` if you want)
6. `git push`

2024-08-27 10:05 UTC, knakamura13 commented
I think the CI tests failed because the class names like `GeometricDecay` need to be removed from the `__init__.py` files and the new names need to be added to those files.

2024-08-28 04:53 UTC, gitongah commented on src/mlrose_ky/algorithms/decay/__init__.py
> +from .geometric_decay import GeometricDecay, GeomDecay
Thank you for pointing that out. I’ve removed GeometricDecay from the imports since it no longer exists.

2024-09-02 07:16 UTC, knakamura13 commented
Fixed the problems with miss-named class instances and all tests are passing now. 
I'll merge this PR, but want to note that there are other classes that still need to be renamed in #7. 

Thanks for the help on this!

2024-09-02 07:17 UTC, merged